### ISSUE TITLE
Can't install using latest packages on Debian?

### ISSUE THREAD

**Issue by cehib** [h9k/magirc#126]
```
Checking PHP PDO mysql driver... Missing!
This component is required to run MagIRC. Please contact your Administrator.
Checking PHP mcrypt extension... Missing!
This component is required to run MagIRC. Please contact your Administrator.
```

```
# apt-get install php5-mysql
Reading package lists... Done
Building dependency tree       
Reading state information... Done
php5-mysql is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 68 not upgraded.
```

```
# apt-get install php5-mcrypt
Reading package lists... Done
Building dependency tree       
Reading state information... Done
php5-mcrypt is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 68 not upgraded.
```

Also, I am using latest Anope as standalone stats using the provided example but how can I load the required `chanstats` module (as suggested by MagIRC)?

`chanstats` module says must have ChanServ/NickServ but I don't want these.

I just want it like the old Denora, where we add chanstats channels using the StatServ bot, not ChanServ?

**Comment by h9k** [comment]
It should work fine. Probably, the mysql and mcrypt modules are not loaded in php.ini? You can check the phpinfo(); output and see if these modules are mentioned.
As far as Anope goes, I'm not really familiar with the setup. But yes, if you want the chanstats feature you need ChanServ and NickServ because chanstats is tied to those services.

**Comment by Sheogorath-SI** [comment]
Don't forget to restart apache after installing php modules.

**Comment by know75** [comment]
Oddly, I've just spent two days trying to move from Denora to Anope too. I had a lot of troubles on Centos 7 (64 bit), but have finally got it to where everything works apart from Servers > Info. Denora would show the MOTD, current and max users, last netsplit etc. All I have detailed now is that the server is online and the server description. Servers > Countries (or Clients) works fine.

I'm writing in this thread, because I'm wondering if this is another thing Anope doesn't collect/store in the MYSQL database, as Anope debug logs are not showing any errors and the database doesn't appear to have section for specific server information details.

Using Anope as standalone statistics collector, means so much data is missing in Magirc it's hardly worth using. Even using it with a full version of Anope (I'm using the latest: 2.0.3), it's still not as useful as Denora as it's only registered users that appear in User sections.

I don't know Magirc's relationship with the author of Denora, but is there any chance in the future work on Denora could resume? It just works so much better (aside from its current bugs), and is easy to set up. Right now I'm switching back to Denora. Anope and Magirc don't really make very good partners in my opinion.

**Comment by h9k** [comment]
Yeah, unfortunately it was decided not to include the MOTD and split features, among a couple of others, into Anope.
As far as chanstats goes it's true, Anope only tracks registered users. It is the more reliable way and has some advantages tied to ChanServ and NickServ. But I understand that people might prefer the old way Denora did things.
Unfortunately Denora is no longer maintained due to lack of time. But the community is free to fork the code and continue on. The thing with Denora is, it is based on a really old Anope version and it would require some work to get it where it should be.

**Comment by cehib** [comment]
Ah, that sucks then.

Our site uses SQLAuth so we have no interest in loading ChanServ/NickServ.

At this point I think we will revert back to Denora, even though it is no longer maintained, at least it works as we need. The Anope method seems a bit half-arsed with things not working.

Keep up great work on MagIRC.
