### ISSUE TITLE
i can't identifity on my panel admin

### ISSUE THREAD

**Issue by amoutai** [h9k/magirc#137]
I use magirc with nginx and I can not authenticate in my panel admin.

My conf : https://pastebin.com/hQc6WZ6p

It does not move from the page https://magirc.test.fr/admin/index.php ..

Thank you for helping me please

**Comment by h9k** [comment]
If you are familiar with Firefox and the Firebug extension, you could try to enable Firebug and see if any errors happen in the console when trying to log in

**Comment by amoutai** [comment]
hello h9k,

try with https://magirc.chaat.fr/admin/ , I have no error in console and my log nginx

**Comment by h9k** [comment]
Indeed there seems to be a problem... https://magirc.chaat.fr/admin/index.php/ajaxlogin actually shows https://magirc.chaat.fr/index.php instead of the login page... I am not familiar with nginx, but it seems like a config problem.
Maybe you can try to copy the conf/anope.cfg.dist.php to conf/anope.cfg.php, edit it, and see if the magirc pages work, so we can see if the problem is related to the admin panel only.

**Comment by amoutai** [comment]
I have made the change

Maybe the problem comes from rewrite?

**Comment by h9k** [comment]
Yeah, something is wrong.
https://magirc.chaat.fr/index.php/user works for example
but https://magirc.chaat.fr/admin/index.php/ajaxlogin and https://magirc.chaat.fr/rest/service.php/users/activity/monthly are broken, nginx seems to redirect the requests to the main index.php, which is wrong.
So definetly a config problem... just need to find out what it is, as I have zero knowledge about nginx :(

**Comment by amoutai** [comment]
We need to change the rewrite : 

location ~ \.php {
in
location ~ ^(/.*\.php)(/.*)?$ {

**Comment by h9k** [comment]
Thanks for pointing out, will update the docs
