### ISSUE TITLE
Magirc is not complete

### ISSUE THREAD

**Issue by amoutai** [h9k/magirc#141]
Hi,

I do not know why I do not have all the information of magirc on https://magirc.test.fr

Thank you for your future answers.

**Comment by h9k** [comment]
Look at https://magirc.chaat.fr/rest/service.php/network/status, it says an anope table is missing... probably your anope install is not complete, I suspect you did not enable the irc2sql module.

**Comment by amoutai** [comment]
Ok thanks :)

**Comment by amoutai** [comment]
I have irc2sql to install but it still does not work ..

**Comment by h9k** [comment]
Meanwhile I see you partially fixed the issue. However, I see the peak values are not present.
For this, you need to execute the magirc/setup/sql/anope.sql in your anope database, this will create things needed by magirc. Magirc setup does this automatically, but since tables were missing it probably failed.
So just execute the contents of that file manually and it should work. Perhaps you need to wait up to one hour for all values to show up.

**Comment by amoutai** [comment]
My maxusage table stays at 0 : http://i.imgur.com/uRWf5m7.png

And I have certain values that do not move : http://i.imgur.com/UERozOW.png

I have executed in my table anope the contents of anope.sql

**Comment by amoutai** [comment]
no idea?

**Comment by h9k** [comment]
No idea I am afraid, best thing is to seek support from the Anope guys, as this is an issue with your Anope install.

**Comment by amoutai** [comment]
Ok thank you, can change my link in your first comment "chaat.fr" in "test.fr" thanks :)
