### ISSUE TITLE
Language not changing

### ISSUE THREAD

**Issue by TheMythPT** [h9k/magirc#145]
Somehow, the language packages aren't working properly.
I've installed it via git clone, composer install and bower install.
i have the issue in all browsers that i have:
Chrome, Chromium and FireFox (Xubuntu 16.04.2).
Any help would be highly appreciated.
You can test if you have the same issue here:
http://stats.ptirc.org

**Comment by h9k** [comment]
Hello, the problem seems to be that you are missing the corresponding locales on the server.
However, MagIRC was supposed to work around this problem, but it seems to no longer work.
I will investigate if there is anything I can do. But if you have root access to the server, you can add the locales and you should be fine.

**Comment by TheMythPT** [comment]
locales added and now all seems to work properly.
but now  new problem arises:
![no_data1](https://user-images.githubusercontent.com/25697531/27854782-5416f18c-6168-11e7-85eb-f0d327b37024.png)
what could be causing this?
Any help would be appreciated.

**Comment by TheMythPT** [comment]
okay. found the problem. somehow, with anope migration from one machine to the other, the chanstats otpion disappeared from the users.
all working properly now.
